# Plex Server
# https://hub.docker.com/r/linuxserver/plex
#
# Notes:
# - Web server is found at http://<your-ip>:32400/web
# - Media files are stored on a NAS
# - A path to the NAS is mounted as /media-share

version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /opt/plex:/config
      - /media-share/tv:/tv
      - /media-share/movies:/movies
    restart: unless-stopped
