#
# This YAML file defines a Kubernetes Pod named "support-pod-node" in the "default" namespace.
# The pod runs an Ubuntu container with several useful networking and system utilities installed.
# It is designed to be scheduled onto a specific node and can be used for troubleshooting and support tasks.
#
# Features:
# - Runs an Ubuntu container with tools like netcat, telnet, dnsutils, curl, ping, and git.
# - Uses a simple infinite loop to keep the container running.
# - Requests and limits for CPU and memory resources are defined.
# - The pod is scheduled onto a specific node using the nodeName field.
#
# Usage:
# - Apply this YAML file to your Kubernetes cluster using `kubectl apply -f support-pod-node.yaml`.
# - Use `kubectl exec` to run commands inside the pod for troubleshooting and support tasks.
#
# Example:
# kubectl apply -f support-pod-node.yaml
# kubectl exec -it support-pod-node -- /bin/bash
#
apiVersion: v1
kind: Pod
metadata:
  name: support-pod-node
  namespace: default
spec:
  containers:
  - name: support-pod-node
    image: ubuntu:latest
    command:
      - "/bin/bash"
      - "-c"
      - |
        apt-get update && \
        apt-get install -y netcat-openbsd telnet dnsutils curl iputils-ping git && \
        while true; do sleep 3600; done
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  nodeName: aks-nodename-13402868-vmss000003
